# Generated by Django 5.2.2 on 2025-06-13 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='word_column',
            new_name='word_count',
        ),
    ]
