# Generated by Django 5.2.2 on 2025-06-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_word_column_article_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'published'), ('in_progress', 'in progress'), ('published', 'published')], default='draft', max_length=20),
        ),
    ]
